FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.Geometry" = "*", "Sedulous.Models" = "*", "Sedulous.Imaging" = "*", "Sedulous.Serialization" = "*", "Sedulous.Serialization.OpenDDL" = "*", "Sedulous.Mathematics.Serialization" = "*", "Sedulous.Renderer" = "*", "Sedulous.Animation" = "*", "Sedulous.Animation.Resources" = "*", "Sedulous.Geometry.Resources" = "*", "Sedulous.Textures.Resources" = "*", "Sedulous.Materials" = "*", "Sedulous.Materials.Resources" = "*"}

[Project]
Name = "Sedulous.Geometry.Tooling"
