FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Engine.Runtime" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.RendererNG" = "*", SampleFramework = "*"}

[Project]
Name = "RendererNGSandbox"
StartupObject = "RendererNGSandbox.Program"
