FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Logging" = "*", "Sedulous.RHI" = "*", "Sedulous.Resources" = "*", "Sedulous.Geometry" = "*", "Sedulous.Imaging" = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Renderer" = "*", "Sedulous.Shaders" = "*", "Sedulous.Animation" = "*"}

[Project]
Name = "Sedulous.Engine.Renderer"
