FileVersion = 1
Dependencies = {corlib = "*", "SampleFramework" = "*", "Sedulous.Framework.Renderer" = "*", "Sedulous.Geometry" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "RendererScene"
TargetType = "BeefConsoleApplication"
StartupObject = "RendererScene.Program"
