FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Editor.App" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Logging" = "*"}

[Project]
Name = "Sedulous.Editor.Runner"
TargetType = "BeefConsoleApplication"
StartupObject = "Sedulous.Editor.Runner.Program"
