FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Engine.Runtime" = "*", "Sedulous.RendererNG" = "*"}

[Project]
Name = "RendererNGIntegrated"
StartupObject = "RendererNGIntegrated.Program"
