FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Framework.Scenes" = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Audio" = "*"}

[Project]
Name = "Sedulous.Framework.Audio"
TargetType = "BeefLib"
