FileVersion = 1
Dependencies = {corlib = "*", SampleFramework = "*", "Sedulous.Engine.Renderer" = "*", "Sedulous.Geometry" = "*"}

[Project]
Name = "RendererGeometry"
StartupObject = "RendererGeometry.Program"
