FileVersion = 1
Dependencies = {corlib = "*", "RHI.SampleFramework" = "*", "Sedulous.Framework.Renderer" = "*", "Sedulous.Geometry" = "*", "Sedulous.Imaging" = "*", "Sedulous.Models" = "*", "Sedulous.Models.GLTF" = "*"}

[Project]
Name = "RendererGeometry"
TargetType = "BeefConsoleApplication"
StartupObject = "RendererGeometry.Program"
