FileVersion = 1
Dependencies = {corlib = "*", "SampleFramework" = "*", "Sedulous.Framework.Renderer" = "*", "Sedulous.Geometry" = "*"}

[Project]
Name = "RendererGeometry"
StartupObject = "RendererGeometry.Program"
