FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Resources" = "*", "Sedulous.Serialization" = "*", "Sedulous.UI" = "*", "Sedulous.Drawing" = "*"}

[Project]
Name = "Sedulous.Editor.Core"
TargetType = "BeefLib"
