FileVersion = 1

[Project]
Name = "Sedulous.Tooling"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.Foundation" = "*"
"Sedulous.Mathematics" = "*"
"Sedulous.RHI" = "*"
"Sedulous.UI" = "*"
"Sedulous.UI.FontRenderer" = "*"
