FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*"}

[Project]
Name = "Sedulous.Framework.Animation"
TargetType = "BeefLib"
