FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Shell" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Engine.Input"
TargetType = "BeefLib"
StartupObject = "Sedulous.Engine.Input.Program"
