FileVersion = 1
Dependencies = {corlib = "*", "RHI.SampleFramework" = "*", "Sedulous.Framework.Renderer" = "*", "Sedulous.Geometry" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "RendererLighting"
TargetType = "BeefConsoleApplication"
StartupObject = "RendererLighting.Program"
