FileVersion = 1
Dependencies = {corlib = "*", "SampleFramework" = "*", "Sedulous.Engine.Renderer" = "*", "Sedulous.Geometry" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "RendererLighting"
TargetType = "BeefConsoleApplication"
StartupObject = "RendererLighting.Program"
