FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.RHI" = "*", "Sedulous.Shaders" = "*"}

[Project]
Name = "Sedulous.Materials"
TargetType = "BeefLib"
StartupObject = "Sedulous.Materials.Program"
