FileVersion = 1
Dependencies = {corlib = "*", "SampleFramework" = "*", "Sedulous.Framework.Renderer" = "*", "Sedulous.Geometry" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "RendererShadow"
TargetType = "BeefConsoleApplication"
StartupObject = "RendererShadow.Program"
