FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.HLSLShaderCompiler" = "*", "Sedulous.Drawing" = "*", "Sedulous.Mathematics" = "*"}

[Project]
Name = "Sedulous.UI.Renderer"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI.Renderer.Program"
