FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI" = "*", "Sedulous.Shaders" = "*", "Sedulous.Drawing" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Profiler" = "*"}

[Project]
Name = "Sedulous.Drawing.Renderer"
TargetType = "BeefLib"
