FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Serialization" = "*", "Sedulous.Framework.Serialization" = "*", "Sedulous.Jobs" = "*", "Sedulous.Resources" = "*", "Sedulous.Logging" = "*", "Sedulous.Serialization.OpenDDL" = "*"}

[Project]
Name = "Sedulous.Framework.Core"
TargetType = "BeefLib"
StartupObject = "Sedulous.Framework.Core.Program"
