FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Jobs" = "*", "Sedulous.Logging" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Profiler" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "Sedulous.Framework.Core"
TargetType = "BeefLib"
