FileVersion = 1
Dependencies = {corlib = "*", "SampleFramework" = "*", "Sedulous.Engine.Renderer" = "*", "Sedulous.Geometry" = "*", "Sedulous.Imaging" = "*"}

[Project]
Name = "RendererPBR"
TargetType = "BeefConsoleApplication"
StartupObject = "RendererPBR.Program"
