FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Logging" = "*", "Sedulous.RHI" = "*", "Sedulous.UI" = "*", "Sedulous.UI.FontRenderer" = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Framework.Renderer" = "*"}

[Project]
Name = "Sedulous.Framework.UI"
TargetType = "BeefLib"
