FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Profiler" = "*"}

[Project]
Name = "Sedulous.Framework.Scenes"
TargetType = "BeefLib"
