FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.Render" = "*", "Sedulous.Geometry" = "*", "Sedulous.Geometry.Tooling" = "*", "Sedulous.Models.GLTF" = "*", "Sedulous.Animation" = "*", "Sedulous.Framework.Runtime" = "*"}

[Project]
Name = "RenderSandbox"
StartupObject = "RenderSandbox.Program"
