FileVersion = 1
Dependencies = {corlib = "*", SampleFramework = "*", "Sedulous.Engine.Core" = "*", "Sedulous.Engine.Renderer" = "*", "Sedulous.Geometry" = "*", "Sedulous.Geometry.Tooling" = "*", "Sedulous.Imaging" = "*", "Sedulous.Logging" = "*", "Sedulous.Models" = "*", "Sedulous.Models.GLTF" = "*"}

[Project]
Name = "RendererAsset"
StartupObject = "RendererAsset.Program"
