FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Geometry" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Imaging" = "*", "Sedulous.RHI" = "*", "Dxc-Beef" = "*"}

[Project]
Name = "Sedulous.RendererNG"
TargetType = "BeefLib"
StartupObject = "Sedulous.RendererNG.Program"
