FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.Imaging" = "*", "Sedulous.RHI" = "*", "RHI.SampleFramework" = "*"}

[Project]
Name = "RHIMipmaps"
StartupObject = "RHIMipmaps.Program"
