FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Framework.Scenes" = "*"}

[Project]
Name = "Sedulous.Framework.Scenes.Tests"
TargetType = "BeefTest"
