FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Drawing" = "*", "Sedulous.Fonts" = "*", "Sedulous.Fonts.TTF" = "*", "Sedulous.RHI" = "*"}

[Project]
Name = "Sedulous.Drawing.Fonts"
TargetType = "BeefLib"
