FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Animation" = "*", "Sedulous.Resources" = "*", "Sedulous.Geometry" = "*", "Sedulous.OpenDDL" = "*", "Sedulous.Serialization.OpenDDL" = "*", "Sedulous.Mathematics.Serialization" = "*"}

[Project]
Name = "Sedulous.Animation.Resources"
TargetType = "BeefLib"
StartupObject = "Sedulous.Animation.Resources.Program"
