FileVersion = 1

[Project]
Name = "Sedulous.Fonts.Tests"
TargetType = "BeefTest"

[Dependencies]
corlib = "*"
"Sedulous.Foundation" = "*"
"Sedulous.Mathematics" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
