FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "stb_truetype-Beef" = "*"}

[Project]
Name = "Sedulous.UI.FontRenderer"
TargetType = "BeefLib"
