FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.Imaging" = "*", "Sedulous.RHI" = "*", "SampleFramework" = "*"}

[Project]
Name = "RHITexturedQuad"
StartupObject = "RHITexturedQuad.Program"
