FileVersion = 1
Dependencies = {corlib = "*", SampleFramework = "*", "Sedulous.Engine.Renderer" = "*", "Sedulous.Geometry" = "*", "Sedulous.Geometry.Tooling" = "*", "Sedulous.Imaging" = "*", "Sedulous.Models" = "*", "Sedulous.Models.GLTF" = "*", "Sedulous.Resources" = "*"}

[Project]
Name = "RendererSkinned"
StartupObject = "RendererSkinned.Program"
