FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Fonts" = "*", "Sedulous.Resources" = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Fonts.Resources"
TargetType = "BeefLib"
