FileVersion = 1

[Project]
Name = "stb_vorbis-Beef"
TargetType = "BeefLib"
StartupObject = "stb_vorbis.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/stb_vorbis.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/stb_vorbis.lib"]
