FileVersion = 1

[Project]
Name = "Sedulous.Models.GLTF"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.Mathematics" = "*"
"Sedulous.Models" = "*"
"Sedulous.Imaging" = "*"
"cgltf-Beef" = "*"
