FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.AppFramework" = "*", "Sedulous.Models" = "*", "Sedulous.Models.GLTF" = "*"}

[Project]
Name = "GLTFViewer"
StartupObject = "GLTFViewer.Program"
