FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Geometry" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Imaging" = "*", "Sedulous.RHI" = "*", "Sedulous.Shaders" = "*"}

[Project]
Name = "Sedulous.Renderer"
TargetType = "BeefLib"
StartupObject = "Sedulous.Renderer.Program"
