FileVersion = 1

[Project]
Name = "joltc-Beef"
TargetType = "BeefLib"
StartupObject = "joltc_Beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/joltcd.lib", "$(ProjectDir)/dist/Debug-Win64/joltd.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Debug-Win64/*.dll\")", "CopyToDependents(\"$(ProjectDir)/dist/Debug-Win64/*.pdb\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/joltc.lib", "$(ProjectDir)/dist/Release-Win64/jolt.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Release-Win64/*.dll\")", "CopyToDependents(\"$(ProjectDir)/dist/Release-Win64/*.pdb\")"]

[Configs.Test.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/joltcd.lib", "$(ProjectDir)/dist/Debug-Win64/joltd.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/Debug-Win64/*.dll\")", "CopyToDependents(\"$(ProjectDir)/dist/Debug-Win64/*.pdb\")"]