FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Collections" = "*", "Sedulous.Logging" = "*"}

[Project]
Name = "Sedulous.UI"
TargetType = "BeefLib"
