FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework.Core" = "*", "Sedulous.Framework.Scenes" = "*", "Sedulous.Framework.Render" = "*", "Sedulous.Foundation" = "*", "Sedulous.Mathematics" = "*", "Sedulous.Physics" = "*", "Sedulous.Render" = "*"}

[Project]
Name = "Sedulous.Framework.Physics"
TargetType = "BeefLib"
