FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Engine.Core" = "*", "Sedulous.UI" = "*", "Sedulous.UI.Renderer" = "*", "Sedulous.Mathematics" = "*", "Sedulous.RHI" = "*", "Sedulous.Drawing" = "*", "Sedulous.Serialization" = "*"}

[Project]
Name = "Sedulous.Engine.UI"
TargetType = "BeefLib"
