FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "dr_libs-Beef"
TargetType = "BeefLib"
StartupObject = "dr_libs_Beef.Program"

[[ProjectFolder.Items]]
Type = "IgnoreSource"
Name = "dr_mp3.bf"

[[ProjectFolder.Items]]
Type = "IgnoreSource"
Name = "dr_wav.bf"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/dr_flac.lib"]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/dr_mp3.lib"]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/dr_wav.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/dr_flac.lib"]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/dr_mp3.lib"]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/dr_wav.lib"]