FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.AppFramework" = "*", "Sedulous.Editor.Core" = "*", "Sedulous.UI" = "*", "Sedulous.Drawing" = "*", "Sedulous.Foundation" = "*", "Sedulous.Logging" = "*"}

[Project]
Name = "Sedulous.Editor.App"
TargetType = "BeefLib"
