FileVersion = 1

[Project]
Name = "Sedulous.Physics.Tests"
TargetType = "BeefTest"

[Dependencies]
corlib = "*"
"Sedulous.Foundation" = "*"
"Sedulous.Mathematics" = "*"
"Sedulous.Physics" = "*"
"Sedulous.Physics.Jolt" = "*"
