FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Shell" = "*", "Sedulous.Shell.SDL3" = "*", "Sedulous.UI" = "*", "Sedulous.UI.Shell" = "*", "Sedulous.UI.Fonts" = "*", "Sedulous.UI.Renderer" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Drawing" = "*", "Sedulous.Fonts" = "*", "Sedulous.Mathematics" = "*"}

[Project]
Name = "Sedulous.AppFramework"
TargetType = "BeefLib"
StartupObject = "Sedulous.AppFramework.Program"
