FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Mathematics" = "*", "Sedulous.RHI" = "*", "RHI.SampleFramework" = "*"}

[Project]
Name = "RHIInstancing"
StartupObject = "RHIInstancing.Program"
